on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  backend_test:
    name: rest assured mvn test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Tests
        run: | 
             cd restAssuredDemo
             mvn test
             
  frontend_test:
    needs: backend_test
    name: selenium mvn test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Tests
        run: | 
             cd SeleniumDemo
             mvn test
             
  k6_load_test:
    needs: [backend_test,frontend_test]
    name: k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run k6 load test
        uses: k6io/action@v0.1
        with:
          filename: PSRTestDemo/demo.js

  postman_newman_test:
    needs: [backend_test,frontend_test,k6_load_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm install -g newman
      - run: newman run PostmanDemo/PostmanDemo.postman_collection.json
      
      - name: Storing report
        uses: actions/upload-artifact@v2
        with:
          name: Newman report
          path: PostmanDemo/report.html
          retention-days: 2
